# Generated by Django 5.2 on 2025-10-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='item_id',
            new_name='institution_id',
        ),
    ]
